### PR TITLE
update path for virtual-dc scripts

### PR DESCRIPTION
**Pull request by jarededwards**
## Description
fixes path for executing scripts

### CODE REVIEW

**Comment by douglasmakey** [comment]
Currently, when you use `make dc` to create the datacenter, at the end of the process you end up in an SSH connection to the laptop. If you exit the laptop, you will be in the `colony-vagrant` folder. However, if you use `make-dc` to make an SSH connection to the datacenter-vm, you will end up in the `root` folder, so you will need to change the path. That was my confusion because I never exit the laptop after the datacenter is created. I always use make-dc to make an SSH connection to the datacenter-vm. So, we need to decide which flow we are going to support, make a clarification in the README, or just add the full path.

@jarededwards @patrickdappollonio

**Comment by patrickdappollonio** [comment]
Called it! 😆 I trusted you Douglas!!! 😆😆😆

Jokes aside... Part of the conversation we missed today was around if we're going to convert this to Go instead of keeping it as a collection of scripts.

**Review by patrickdappollonio — APPROVED** [review]

**Comment by patrickdappollonio** [comment]
@douglasmakey like your buddy used to say "you're holding it wrong" 😆

**Comment by jarededwards** [comment]
@douglasmakey / @patrickdappollonio could we adjust the `.bashrc` to automatically `cd colony-vagrant` for those new ssh connections from the `make dc` command when connecting? 
https://github.com/konstructio/colony-vagrant/blob/3f00c5c203ff204ecc94e3bdb0f0a1b22a409d16/virtual-datacenter/scripts/functions.sh#L37

**Comment by patrickdappollonio** [comment]
Note for myself here:

`~/.bash_profile` or `~/.profile`:
* Executed for login shells (e.g., when you log in via SSH).
* Ideal for commands that should run only once at the start of a login session.

`~/.bashrc`:
* Executed for non-login interactive shells (e.g., when you open a new terminal window within a graphical session).
* Suitable for commands and aliases you want available in every interactive shell.

**Comment by patrickdappollonio** [comment]
Closing in favor of #11

**Pull request closed without merging**
